from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.dml import MSO_THEME_COLOR
from pptx.enum.text import MSO_ANCHOR, MSO_AUTO_SIZE
import os

class PPTGenerator:
    def __init__(self):
        # Define a more varied color palette
        self.color_palette = [
            RGBColor(0, 51, 102),     # Dark blue
            RGBColor(0, 100, 0),      # Dark green
            RGBColor(139, 69, 19),    # Brown
            RGBColor(0, 0, 139),      # Dark blue
            RGBColor(128, 0, 128),    # Purple
            RGBColor(255, 140, 0),    # Orange
            RGBColor(100, 149, 237),  # Cornflower blue
            RGBColor(220, 20, 60),    # Crimson
        ]
        
    def create_presentation(self, slides_data, output_path):
        """
        Create a PowerPoint presentation from structured data with enhanced formatting
        """
        prs = Presentation()
        
        # Set slide dimensions (16:9 aspect ratio)
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)
        
        # Define color scheme
        title_color = RGBColor(0, 51, 102)  # Dark blue
        content_color = RGBColor(33, 33, 33)  # Dark gray
        
        for i, slide_data in enumerate(slides_data):
            # Use different layouts based on slide type
            if slide_data['type'] == 'title':
                slide_layout = prs.slide_layouts[0]  # Title slide layout
            else:
                slide_layout = prs.slide_layouts[1]  # Title and content layout
            
            slide = prs.slides.add_slide(slide_layout)
            
            # Add title
            title = slide.shapes.title
            title.text = slide_data['title']
            
            # Enhance title formatting
            title.text_frame.paragraphs[0].font.size = Pt(44 if slide_data['type'] == 'title' else 32)
            title.text_frame.paragraphs[0].font.bold = True
            title.text_frame.paragraphs[0].font.color.rgb = title_color
            
            # Add content for non-title slides
            if slide_data['type'] == 'content':
                content_placeholder = slide.placeholders[1]
                
                # Clear existing text
                text_frame = content_placeholder.text_frame
                text_frame.clear()
                
                # Add content as bullet points with varied formatting
                for j, content in enumerate(slide_data['content']):
                    if j == 0:
                        p = text_frame.paragraphs[0]
                    else:
                        p = text_frame.add_paragraph()
                    
                    p.text = content
                    p.font.size = Pt(18)
                    p.font.color.rgb = content_color
                    p.level = 0  # First level bullet
                    p.space_after = Pt(8)  # Add space after each bullet
                    
                    # Use different colors for different bullet points
                    color_index = j % len(self.color_palette)
                    p.font.color.rgb = self.color_palette[color_index]
                    p.font.bold = False
            
            # Add decorative elements
            if slide_data['type'] != 'title':
                # Add a colored header bar
                left = Inches(0)
                top = Inches(1.2)
                width = Inches(13.33)
                height = Inches(0.1)
                
                header_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
                fill = header_bar.fill
                fill.solid()
                color_index = i % len(self.color_palette)
                fill.fore_color.rgb = self.color_palette[color_index]
                
                # Add slide number and footer
                if i == 0:  # Add footer only on first slide
                    footer = slide.shapes.add_textbox(Inches(0.5), Inches(7.0), Inches(12), Inches(0.3))
                    footer.text = "Generated by Agentic AI PPT Maker"
                    footer.text_frame.paragraphs[0].font.size = Pt(10)
                    footer.text_frame.paragraphs[0].font.color.rgb = RGBColor(150, 150, 150)
                    footer.text_frame.paragraphs[0].alignment = PP_ALIGN.LEFT
                
                # Add slide number
                slide_number = slide.shapes.add_textbox(Inches(12), Inches(7.2), Inches(1), Inches(0.3))
                slide_number.text = f"{i+1}/{len(slides_data)}"
                slide_number.text_frame.paragraphs[0].font.size = Pt(12)
                slide_number.text_frame.paragraphs[0].font.color.rgb = RGBColor(100, 100, 100)
            else:
                # Add slide number for title slide
                slide_number = slide.shapes.add_textbox(Inches(12), Inches(7.2), Inches(1), Inches(0.3))
                slide_number.text = f"{i+1}/{len(slides_data)}"
                slide_number.text_frame.paragraphs[0].font.size = Pt(12)
                slide_number.text_frame.paragraphs[0].font.color.rgb = RGBColor(100, 100, 100)
        
        prs.save(output_path)
        return output_path